# Generated by Django 5.0.6 on 2024-07-23 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_cursos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyect',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='proyecto',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='proyecto',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='titulo',
            new_name='title',
        ),
    ]
