# Generated by Django 5.0.6 on 2024-07-23 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_rename_proyect_project_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cursos',
            new_name='Course',
        ),
    ]
