# Generated by Django 5.0.6 on 2024-08-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
