# Generated by Django 5.0.6 on 2024-08-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_course_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='miapp.course'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
