# Generated by Django 5.0.6 on 2024-09-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_clientealumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='clientealumno',
            name='curso',
        ),
        migrations.AddField(
            model_name='clientealumno',
            name='curso',
            field=models.ManyToManyField(blank=True, to='miapp.course'),
        ),
    ]
