# Generated by Django 5.0.6 on 2024-09-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientealumno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='curso',
        ),
        migrations.AddField(
            model_name='clientealumno',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.course'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.course'),
        ),
    ]
