# Generated by Django 5.0.6 on 2024-09-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_remove_clientealumno_curso_remove_movimiento_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_movimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
