# Generated by Django 5.0.6 on 2024-09-14 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0015_alter_movimiento_fecha_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='tarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.task'),
        ),
    ]
