# Generated by Django 5.0.6 on 2024-09-20 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0016_movimiento_tarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.IntegerField()),
                ('alumno_nombre', models.CharField(max_length=255)),
                ('curso_name', models.CharField(blank=True, max_length=100, null=True)),
                ('proyecto_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.course')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miapp.project')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.tipomovimiento')),
            ],
        ),
    ]
