# Generated by Django 5.0.6 on 2024-09-26 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0017_movimientotemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientotemporal',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
