# Generated by Django 5.0.6 on 2024-09-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0018_alter_movimientotemporal_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_movimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
