# Generated by Django 5.0.6 on 2024-09-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0019_alter_movimiento_fecha_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_movimiento',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
