# Generated by Django 5.1.1 on 2024-10-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0020_alter_movimiento_fecha_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientotemporal',
            name='tareas_asignadas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
