# Generated by Django 5.0.1 on 2024-10-15 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0022_movimiento_hecho_movimientotemporal_hecho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientotemporal',
            name='tareas_asignadas',
        ),
        migrations.AddField(
            model_name='movimientotemporal',
            name='tarea_asignada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='miapp.task'),
        ),
    ]
